version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment: #TODO: MOVE TO SECRETS
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=mydb
      - SERVICE_PORT=:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest # TODO: FIX VERSION
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "0.0.0.0:5432:5432" #for debug purposes
    # TODO: volumes and storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"] # TODO: MOVE TO SECRETS 
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate # TODO: FIX VERSION
    container_name: postgres_migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://user:password@db:5432/mydb?sslmode=disable", #TODO: Move to secrets
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    restart: "no"